name: Get Channel Configs

on:
  schedule:
    - cron: "0 */3 * * *"
  push:
  workflow_dispatch:

jobs:
  Getting-Configs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
          cache: "pip"
      - run: |
          pip install -r requirements.txt
          python Grabber.py
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
          git config credential.helper store
          git add -A .
          git commit -m "🐈 Last Run - $(TZ='Asia/Tehran' date '+%Y-%m-%d %H:%M:%S')"
          git push
